newsapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from newsapp.views import *
import django.contrib
from django.urls import include, path
from newsapp import views

app_name = "newsapp"
urlpatterns = [


    # client url
    # client url
    # client url
    # client url
    # path('base/',ClientBaseView.as_view(),name='clientbase'),
    path('', ClientHomeView.as_view(), name='clienthome'),
    path('video/',VideoGalleryView.as_view(),name='videogallery'),
    path('news/<int:pk>/detail/',
         ClientNewsDetailView.as_view(), name='clientnewsdetail'),
    path('news/category/<int:pk>/detail/', ClientCategoryDetailView.as_view(),
         name='clientcategorydetail'),
    path('news/popular/list/', PopularNewsListView.as_view(),
         name='popularnewslist'),
    path('news/mostcommented/list/', MostCommentedNewsListView.as_view(),
         name='mostcommentednewslist'),
    path('client/subcategory/<int:pk>/detail/',
         ClientSubcategoryDetailView.as_view(), name='clientsubcategory'),
    path('editor/<int:pk>/detail/',
         EditorDetailView.as_view(), name='editornewsdetail'),
    path('search/', SearchView.as_view(), name='searched'),
    path('contact/', ClientContactView.as_view(), name='clientcontact'),
    path('about/',ClientAboutView.as_view(),name='clientabout'),
    path('privacy/policy/',OrganizationPrivacyView.as_view(),name='organizationprivacy'),



    path('subscriber/', SubscriberView.as_view(), name='subscriber'),
    path('commentcreate/<int:pk>/',
         CommentCreateView.as_view(), name='commentcreate'),
    # path('news/<int:pk>/detail/',
    #      ClientNewsDetailView.as_view(), name='clientnewsdetail'),
    # editor url
    # editor url
    # editor url
    # editor url


    path('editor/', EditorHomeView.as_view(), name='editorhome'),
    path('editor/newslist/', EditorNewsList.as_view(), name='newslist'),

    # editor news
    # editor news 
    # editor news
    # editor news
    path('editor/<int:pk>/newsdetail',
         EditorNewsDetailView.as_view(), name='newsdetail'),
    path('ajax/load-subcategories/', views.load_subcategories,
         name='load_subcategories'),
    path('editor/newsadd/',
         EditorNewsCreate.as_view(), name='newsadd'),
    path('editor/<int:pk>/newsupdate/',
         EditorNewsUpdate.as_view(), name='newsupdate'),
    path('editor/<int:pk>/newsdelete/',
         EditorNewsDelete.as_view(), name='newsdelete'),
    path('editor-registration/',
         EditorRegistrationView.as_view(), name='editorregistration'),
    path('login/',
         LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('admin/<int:pk>/edit/', EditUserProfileView.as_view(),
         name="edit-user-profile"),
    path('editor/<int:pk>/edit/', EditUsersProfileView.as_view(),
         name="editor-user-profile"),
    path("password/change/",
         PasswordChangeView.as_view(), name="passwordchange"),
    path("editor-password/change/",
         EditorPasswordChangeView.as_view(), name="editorpasswordchange"),


    # admin url
    # admin url
    # admin url
    # admin url

    # admin advertizementposition
    # admin advertizementposition
    # admin advertizementposition
    # admin advertizementposition

    path('adminhome/', AdminView.as_view(), name='adminhome'),
    path('admin/adminadvetizementposition',
         AdminAdvertizementPositionList.as_view(), name='advertizementposition'),
    path('admin/advertizementpositionadd',
         AdminAdvertizementPositionCreate.as_view(), name='advertizementpositionadd'),
    path('admin/<int:pk>/advertizementpositionupdate',
         AdminAdvertizementPositionUpdate.as_view(), name='advertizementpositionupdate'),
    path('admin/<int:pk>/advertizementpositiondelete',
         AdminAdvertizementPositionDelete.as_view(), name='advertizementpositiondelete'),

    # admin advertizement
    # admin advertizement
    # admin advertizement
    # admin advertizement

    path('admin/adminadvettizement',
         AdminAdvertizementList.as_view(), name='advertizement'),
    path('admin/advertizementadd',
         AdminAdvertizementCreate.as_view(), name='advertizementadd'),
    path('admin/<int:pk>/advertizementupdate',
         AdminAdvertizementUpdate.as_view(), name='advertizementupdate'),
    path('admin/<int:pk>/advertizementdelete',
         AdminAdvertizementDelete.as_view(), name='advertizementdelete'),
    path('admin-registration/', AdminRegistrationView.as_view(),
         name='adminregistration'),

    # admin organizationinformation
    # admin organizationinformation
    # admin organizationinformation
    # admin organizationinformation
    path('admin/organizationinformation',
         AdminOrganizationInformationList.as_view(), name='organizationinformationlist'),

    path('admin/<int:pk>/organizationinformationdetail',
         AdminOrganizationInformationDetail.as_view(), name='organizationinformationdetail'),
    path('admin/<int:pk>/organizationinformationupdate',
         AdminOrganizationInformationUpdate.as_view(), name='organizationinformationupdate'),

    # admin newscategory
    # admin newscategory
    # admin newscategory
    # admin newscategory

    path('admin/newscategory/',
         AdminNewsCategoryList.as_view(), name='adminnewscategory'),
    path('admin/newscategoryadd',
         AdminNewsCategoryCreate.as_view(), name='adminnewscategoryadd'),
    path('admin/<int:pk>/newscategoryupdate/',
         AdminNewsCategoryUpdate.as_view(), name='adminnewscategoryupdate'),
    path('admin/<int:pk>/newscategorydelete/',
         AdminNewsCategoryDelete.as_view(), name='adminnewscategorydelete'),

    # admin newssubcategory
    # admin newssubcategory
    # admin newssubcategory
    # admin newssubcategory

    path('admin/newssubcategorylist/',
         AdminNewsSubCategoryList.as_view(), name='adminnewssubcategorylist'),
    path('admin/newssubcategoryadd',
         AdminNewsSubCategoryCreate.as_view(), name='adminnewssubcategoryadd'),
    path('admin/<int:pk>/newssubcategoryupdate/',
         AdminNewsSubCategoryUpdate.as_view(), name='adminnewssubcategoryupdate'),
    path('admin/<int:pk>/newssubcategorydelete/',
         AdminNewsSubCategoryDelete.as_view(), name='adminnewssubcategorydelete'),


    # admin news
    # admin news
    # admin news
    # admin news

    path('admin/newslist',
         AdminNewsList.as_view(), name='adminnewslist'),
    path('admin/newslist/<int:pk>/', AdminDetailView.as_view(), name='newslist'),
    path('admin/<int:pk>/newsdetail',
         AdminNewsDetailView.as_view(), name='adminnewsdetail'),
    path('admin/newsadd/',
         AdminNewsCreate.as_view(), name='adminnewsadd'),
    path('admin/<int:pk>/newsupdate/',
         AdminNewsUpdate.as_view(), name='adminnewsupdate'),
    path('admin/<int:pk>/newsdelete/',
         AdminNewsDelete.as_view(), name='adminnewsdelete'),

    # admin editor
    # admin editor
    # admin editor
    # admin editor
    path('admin/editorlist',
         EditorList.as_view(), name='editorlist'),
    path('admin/editor',
         EditorDashboardList.as_view(), name='editor'),
    path('admin/editorcreate',
         EditorCreate.as_view(), name='editoradd'),
    path('admin/<int:pk>/editorupdate/',
         EditorUpdate.as_view(), name='editorupdate'),
    path('admin/<int:pk>/editordelete/',
         EditorDelete.as_view(), name='editordelete'),
    path('admin/<int:pk>/editordetail/',
         AdminEditorDetailView.as_view(), name='admineditordetail'),
    path('admin/<int:pk>/detail/',
         AdminDetailsView.as_view(), name='admindetails'),

    # admin admin
    # admin admin
    # admin admin
    # admin admin

    path('admin/adminlist',
         AdminList.as_view(), name='adminlist'),


    path('admineditor/<int:pk>/news-list/',
         AdminEditorNewsListView.as_view(), name='admineditornewslist'),
    path('admineditor/<int:pk>/news-list/detail/',
         AdminEditorNewsListDetailView.as_view(), name='admineditornewslistdetail'),
    path('ajaxadminhome/', AjaxAdminHome.as_view(), name='ajaxadminhome'),


]

newsproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls')),
    path('summernote/', include('django_summernote.urls')),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/clienttemplates/clientabout.html
{% extends 'clienttemplates/clientbase.html' %}
{% block content %}
<div class="container">
		<div class="row">
	{% for organization in organizations|slice:'1' %}
	<div class="col-md-6">
	<img src=" {{organization.featured_photo.url}}" style="width:100%">
</div>
<div class="col-md-6" style="margin-top: 50px">
	<p style="font-family: Arial, Helvetica, sans-serif; font-size: 100%">{{organization.about_us|striptags|safe}}</p>
</div>
	{% endfor %}

</div>
{% endblock %}

templates/clienttemplates/clientcategorydetail.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}

<div class="container">
	<div class="row">
		
		<div class="col-md-8">

			{% for news in filtered_news|slice:'1' %}

			<div class="entity_wrapper">

				<div class="entity_title header_purple">
					<!-- <h1><a target="_blank">{{ news.main_category }}</a></h1> -->
				</div>

				<div class="entity_thumb" style="margin-top: 5px;">
					<img class="img-responsive" src="{{ news.image.url }}" alt="feature-top">
				</div>

				<div class="entity_title">
					<a href="{% url 'newsapp:clientnewsdetail' news.pk %}"><h3> {{ news.title }} </h3></a>
				</div>

				<div class="entity_meta">
					{% if not news.editor %}
					{% else %}
					<a>{{ news.created_at }}</a>, by: <a href="{% url 'newsapp:editornewsdetail' news.editor.id %}">{{ news.editor }}</a>
					{% endif %}
				</div>


				<div class="entity_content">

					{{ news.content|striptags|safe|truncatechars:200 }}
					{{ news.content |truncatechars:200|safe }}

				</div>

				<div class="entity_social">
					<span><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2Fnews%2F16%2Fdetail%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore"><i id="countshares" class="fa fa-share-alt" data-href="http://127.0.0.1:8000/news/{{news.id}}/detail/" data-layout="button" data-size="small"></i></a>Shares</span>
					<!-- <span><i class="fa fa-share-alt"></i>424 <a href="#">Shares</a> </span> -->
				</div>
			</div>
			{% endfor %}

	<!-- 	<div class="widget hidden-xs m30">
		{% for company in advertiselist|slice:':1' %}
			<img class="img-responsive widget_img" src="{{ company.image.url }}" style = "height:60px; width:800px;"  alt="add_one">
		{% endfor %}
		</div> -->


		<div class="row">
			{% for news in filtered_news|slice:'1:' %}
			<div class="col-md-6">
	
				<div class="category_article_body">
						
					<div class="top_article_img">
						<img class="img-fluid" src="{{ news.image.url }}" style = "height:300px; width:350px;" alt="feature-top">
					</div>

					<div class="category_article_title">
						<h5><a href="{% url 'newsapp:clientnewsdetail' news.pk %}">{{ news.title }} </a></h5>
					</div>

					<div class="article_date">
						{% if not news.editor %}
						{% else %}
						<a>{{ news.created_at }}</a>, by: <a href ="{% url 'newsapp:editornewsdetail' news.editor.id %}">{{ news.editor }}</a>
						{% endif %}
					</div>

					<div class="category_article_content">
						{{ news.content|truncatechars:150|safe }}
					</div>

					<div class="article_social">
						<span><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2Fnews%2F16%2Fdetail%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore"><i id="countshares" class="fa fa-share-alt" data-href="http://127.0.0.1:8000/news/{{news.id}}/detail/" data-layout="button" data-size="small"></i></a>Shares</span>
							<!-- <span><a href="#"><i class="fa fa-share-alt"></i>424 </a> Shares</span> -->
		
					</div>

					<br>

				</div>	
			</div>
			{% endfor %}

		







					<div class="category_article_content">
						{{ news.content|truncatechars:150|safe }}
					</div>



		</div>


	
<!--  		
 		<div>
		{% for rootcategory in rootcategorylist %}

		{% if rootcategory.root != None %} 	
		{% for news in clientcategorydetail.news_set.all %} 


		<h1> {{news.main_category }} </h1>
		<h1> {{ news.title }}</h1>
		<h2> {{ news.editor }} </h2>
		<img class="img-fluid" src="{{ news.image.url }}" style = "height:300px; width:350px;" alt="feature-top">


		 {% endfor %} 
		 {% endif %} 
		{% endfor %}
	</div> -->

		
	<!-- 	<div class="widget hidden-xs m30">
			{% for company in advertiselist|slice:'1:2' %}
			<img class="img-responsive widget_img" src="{{ company.image.url }}" style = "height:60px; width:800px;"  alt="add_one">
			{% endfor %}
		</div> -->
		
	</div>


	<div class="col-md-4">
		<div class="widget">
			<div class="widget_title widget_black">
				<h2><a>Popular News</a></h2>
			</div>
			{% for news in popularnews|slice:':4' %}
			<div class="media">

				<div class="media-left">
					<a ><img class="media-object" src="{{ news.image.url }}" style = "height:100px; width:100px;" alt="Generic placeholder image"></a>
				</div>

				<div class="media-body">
					<h3 class="media-heading">
						<a href="{% url 'newsapp:clientnewsdetail' news.pk %}" target="_self"> {{ news.title |truncatechars:60 }}</a>
						{% if not news.editor %}
						{% else %}
					</h3> <span class="media-date"><a>{{ news.created_at }}</a>, by: <a href="{% url 'newsapp:editornewsdetail' news.editor.id %}">{{ news.editor }}</a>
					{% endif %}</span>

					<div class="widget_article_social">
						<span><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2Fnews%2F16%2Fdetail%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore"><i id="countshares" class="fa fa-share-alt" data-href="http://127.0.0.1:8000/news/{{news.id}}/detail/" data-layout="button" data-size="small"></i></a>Shares</span>
<!-- 							<span>
								<a href="single.html" target="_self"> <i class="fa fa-share-alt"></i>424</a> Shares
							</span> -->
					<!-- 	<span>
							<a><i class="fa fa-comments-o"></i>4</a> Comments
						</span> -->
					</div>
				</div>
			</div>
			{% endfor %}
			<!-- <p class="widget_divider"><a href="{% url 'newsapp:popularnewslist' %}" target="_self">More News&nbsp;&raquo;</a></p>
 -->		</div>

	<!-- 	<div class="widget hidden-xs m30">
			<img class="img-responsive adv_img" src="{% static 'clientstatic/img/right_add4.jpg'%}" alt="add_one">
			<img class="img-responsive adv_img" src="{% static 'clientstatic/img/right_add1.jpg'%}" alt="add_one">
			<img class="img-responsive adv_img" src="{% static 'clientstatic/img/right_add2.jpg'%}" alt="add_one">
			<img class="img-responsive adv_img" src="{% static 'clientstatic/img/right_add3.jpg'%}" alt="add_one">
		</div> -->

		<div class="widget hidden-xs m30">
			{% for company in advertiselist %}
			{% if forloop.counter == 2 %}
				<img class="img-responsive widget_img" src="{{ company.image.url }}" alt="add_one">
			{% endif %}
			{% endfor %}
		</div>


		<div class="widget m30">
			<div class="widget_title widget_black">	
				<h2><a>Latest News</a></h2>
			</div>
			{% for news in latestnews|slice:'4' %}
			<div class="media">
				<div class="media-left">
					<a ><img class="media-object" src="{{news.image.url }}" style = "height:125px; width:125px;" alt="Generic placeholder image"></a>
				</div>
				<div class="media-body">
					<h3 class="media-heading">
						<a href="{% url 'newsapp:clientnewsdetail' news.pk %}" target="_self">{{news.title}}</a>
					</h3>
					<div class="media_social">
						{{news.content|striptags|safe|truncatechars:'100'}}
					<!-- 	<span><i class="fa fa-comments-o"></i><a>4</a> Comments</span> -->
					</div>
				</div>
			</div>
			{% endfor %}



		<!-- 	{% for company in advertiselist %}
			{% if forloop.counter == 1 %}
				<div class="widget hidden-xs m30">
					<img class="img-responsive widget_img" src="{{ company.image.url }}" alt="add_one">
				</div>
			{% endif %}
			{% endfor %} -->

<!-- 
			<p class="widget_divider"><a target="_self">More News&nbsp;&nbsp;&raquo; </a></p> -->
		</div>
<!-- 
		<div class="widget m30">
			<div class="widget_title widget_black">
				<h2><a >Editor Corner</a></h2>
			</div>

			{% for editor in newseditor %}
			{% if forloop.counter == 1 %}
				<div class="widget_body">
					{% if editor.image %}
					<img class="img-responsive left" src="{{ editor.image.url }}" style = "height:125px; width:125px;"alt="Generic placeholder image">
					{% else %}
					no image
					{% endif %}
					<p>{{ editor.about }}</p>
				</div>
			{% endif %}
			{% endfor %}
		</div> -->


		<!-- <div class="widget hidden-xs m30">
		{% for company in advertiselist|slice:'2:' %}
			<img class="img-responsive add_img" src="{{ company.image.url }}"  style = "height:190px; width:175px;" alt="add_one">
		{% endfor %}
		</div> -->
	</div>
</div>

{% endblock %}

templates/clienttemplates/clientnewsdetail.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}

<section id="entity_section" class="entity_section">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="entity_wrapper">
					<div class="entity_title">
						<h1>{{clientnewsdetail.title}}<br>|{{clientnewsdetail.view_count}}<i class="fa fa-eye"></i></h1>
						
					</div>
					<div>
						<p class='text-left' style="display: inline-block;">{{clientnewsdetail.created_at|date}}
							{% if not clientnewsdetail.editor %}
							{% else %}
							<a href="{% url 'newsapp:editornewsdetail' clientnewsdetail.editor_id %}"><span class="text-right" style="margin-left: 10px;">By: {{clientnewsdetail.editor.full_name}}</span></a>
							{% endif %}
						</p>
					</div>
					<div class="entity_thumb">
						<img src={{clientnewsdetail.image.url}} class="img-responsive hoverimage" style="width: 100%; object-fit:contain;">
					</div>
					<div class="entity_content">
						{{clientnewsdetail.content|safe}}
					</div>
				</div>

				<div class="related_news">
					<div class="entity_inner__title header_purple">
					<!-- 	<h2>Related News</h2> -->
					</div>
					<div class="row">
						{% for newslist in relatednewslist|slice:'4' %}
						<div class="col-md-6">
							<div class="media">


								<div class="media-left">
									<img class="media-object hoverimage" src="{{newslist.image.url}}" alt="{{newslist.title}}" class='img-responsive' width='200'>
								</div>
								<div class="media-body">
									<span class="tag purple"><a href="" target="_self">{{newslist.main_category}}</a></span>
									<a href="{% url 'newsapp:clienthome' %}" target="_self"><h3 class="media-heading">{{newslist.content|striptags|safe|truncatechars:'50'}}</h3></a>
									{% if not newslist.editor %}
									{% else %}
									<span class="media-date"><{{newslist.created_at|date}}, by: <a href="{% url 'newsapp:editornewsdetail' newslist.editor.id %}">{{newslist.editor.full_name}}</a></span>{% endif %}
									<div class="media_social">

									</div>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
				<div class="readers_comment">
					<div class="entity_inner__title header_purple">
						<h2>Readers Comment</h2>
					</div>

					{% for comment in clientnewsdetail.comment_set.all %}
					<div class="media">
						<div class="media-left">

							<img alt="64x64" class="media-object" data-src="{% static 'clientstatic/img/reader_img1.jpg' %}" src="{% static 'clientstatic/img/reader_img1.jpg' %}" data-holder-rendered="true">
							
						</div>
						<div class="media-body">
							<h2 class="media-heading">{{comment.commenter}}</h2>
							{{comment.comment}}
						</div>
					</div>
					{% endfor %}
					<div>
						<h1>	total comment:{{commentlist1}}</h1>
					</div>
				</div>

				<div class="widget_advertisement">
					<img class="img-responsive" src="{% static 'clientstatic/img/category_advertisement.jpg' %}" alt="feature-top">
				</div>
				<div class="entity_comments">
					<div class="entity_inner__title header_black">
						<h2>Add a Comment</h2>
					</div>
					<div class="entity_comment_from">
						<form method="post" action="{% url 'newsapp:commentcreate' clientnewsdetail.id %}">
							{% csrf_token %}
							<div class="form-group">
								<!-- <input type="text" class="form-control" id="inputName" placeholder="Name"> -->
								{{commentform.commenter}}
							</div>
							<div class="form-group">
								{{commentform.email}}
							</div>
							<div class="form-group comment">
								{{commentform.comment}}
							</div>
							<button type="submit" class="btn btn-submit red">Submit</button>
						</form>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="widget">
					<div class="widget_title widget_black">
						<h2>Popular News</h2>
					</div>
					{% for news in popularnews|slice:'5' %}
					{% if clientnewsdetail.title != news.title %}
					<div class="media">
						<div class="media-left">
							<img class="media-object" src="{{news.image.url}}" alt="{{news.title}}" width="100" height="100">
						</div>
						<div class="media-body">
							<h3 class="media-heading">
								<a href="{% url 'newsapp:clientnewsdetail' news.id %}">
									{{news.title}}</a>
							</h3>
							<p>{{news.content|striptags|safe|truncatechars:'30'}}</p>
							<span class="media-date">{{news.created_at|date}}  
								{% if not news.editor %}
								{% else %}
								<br>
								by:
								<a href="{% url 'newsapp:editornewsdetail' news.editor.id %}">{{news.editor}}</a>
								{% endif %}
							</span>
						</div>
					</div>
					{% endif %}
					{% endfor %}
					<div class="widget m30">
						<div class="widget_title widget_black">
							<h1>Latest News</h1>
						</div>
						{% for  news in  latestnews|slice:'5' %}
						{% if clientnewsdetail.title != news.title %}
						<div class="media">
							<div class="media-left">
								<img class="media-object" src="{{news.image.url}}" alt="{{news.title}}" class="img-responsive" width="100" height="100" style="object-fit:cover;">
							</div>
							<div class="media-body">
								<h3 class="media-heading">
									<a href="{% url 'newsapp:clientnewsdetail' news.id %}" target="_self">{{news.title}}</a>
								</h3>
								<p>{{news.content|striptags|truncatechars:'50'}}</p>
								
							</div>
						</div>
						{% endif %}
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

templates/clienttemplates/clientsubcategorydetail.html
{% extends "clienttemplates/clientbase.html" %}
{% load static %}

{% block content %}




{% endblock %}

templates/clienttemplates/commentcreate.html
<form method="post">
	{% csrf_token %}
	{{commentform.as_p}}
	<buttion>Submit</buttion>
</form>

templates/clienttemplates/editordetail.html
{% extends 'clienttemplates/clientbase.html' %}


{% block content %}


<div class="card">
  <img src="{{ editordetail.image.url }}"  style="width:100%">
  <h1>{{ editordetail.full_name }}</h1>
  <p class="title">{{ editordetail.email }}</p>
  <p>{{ editordetail.address }}</p>
  </div>

  <div class="container"> <h3> About the editor: </h3> <p>{{ editordetail.about }}</p></div>

<div class="container">
	<h1> News </h1>
  {% for news in editordetail.news_set.all %}
  <div class="list">
    <a href="{% url 'newsapp:clientnewsdetail' news.id %}" class="list-group-item list-group-item-action"><h3>{{ news.title }}</h3> <p> {{ news.content}}</p></a>
  </div>
  <br>
  {% endfor %}
</div>

<!-- 	<div  class="container">
	<div class="row">
		<div class="col-md-4">
			<h1> News By : {{ news.editor }} </h1>
			{% for news in editordetail.news_set.all %}
			
			<ul>
				<li> {{ news.title }} </li>
			</ul>
				<p>{{ news.content}}</p>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>
 -->







{% endblock %}

templates/clienttemplates/editornewslist.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}

{% for editor in editornewslist %}

{% for news in editor.news_set.all %}




<h1>{{ news.title }}</h1>
<h3>{{ news.editor }}</h3>
<h3>{{ news.editor.id }} </h3>

{% endfor %}

{% endfor %}

{% endblock %}

templates/clienttemplates/privacypolicy.html
{% extends 'clienttemplates/clientbase.html' %}
{% block content %}
<div class="container" class="card">
<h1 style="text-align: center;"> privacy policy</h1>
{% for policy in privacypolicy %}
<p>{{policy.privacy_policy}}</p>

{% endfor %}
</div>
{% endblock %}

templates/clienttemplates/searchresult.html
{% extends 'clienttemplates/clientbase.html' %}
{% block content %}
<section id="entity_section" class="entity_section">
<div class="container">
	<div class="row">
		<h1 class="text-success">Search Results</h1>
		{% for news in searchednews %}
		<div class="col-md-8">
			<div class="entity_wrapper">
				<div class="entity_title">
					<h1><a href="{% url 'newsapp:clientnewsdetail' news.id %}">{{news.title}}<span class="text-success" style="margin-top: 100px">|News|Category|{{news.main_category.title}}</span></a></h1>
				</div>

				<div class="entity_content">
					<p>{{news.content|striptags|safe|truncatechars:'50'}}</p>
				</div>
				<img src="{{news.image.url}}" width="200px">
				<h1><hr class="line"></h1>
			</div>
		</div>
		{% empty %}
		<h1 class="text-danger">no results found</h1>
{% endfor %}

	</div>
</div>
</section>
<!-- {% for news in searchednews %}
<h1>{{news.title}}</h1>
<h2>{{news.content}}</h2>
{% empty %}
<h1>notfound</h1>
{% endfor %}
{% endblock %} -->

templates/clienttemplates/videogallery.html
  {% extends 'clienttemplates/clientbase.html' %}

   {% block content %}
   <div class="container">
  
   	<div class="row">
  
   {% for video in videogallerys|slice:'4' %}
   <div class="col-md-6">

   	 	
   <h1><a href="{% url 'newsapp:clienthome' %}">{{video.title}}</a></h1>

   <iframe width="560" height="315" src="{{video.video_link}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

  
 
</div>

   {% endfor %}

</div>
</div>
  
 
   {% endblock %}