newsapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from newsapp.views import *
import django.contrib
from django.urls import include, path
from newsapp import views

app_name = "newsapp"
urlpatterns = [


    # client url
    # client url
    # client url
    # client url
    # path('base/',ClientBaseView.as_view(),name='clientbase'),
    path('', ClientHomeView.as_view(), name='clienthome'),
    path('video/',VideoGalleryView.as_view(),name='videogallery'),
    path('news/<int:pk>/detail/',
         ClientNewsDetailView.as_view(), name='clientnewsdetail'),
    path('news/category/<int:pk>/detail/', ClientCategoryDetailView.as_view(),
         name='clientcategorydetail'),
    path('news/popular/list/', PopularNewsListView.as_view(),
         name='popularnewslist'),
    path('news/mostcommented/list/', MostCommentedNewsListView.as_view(),
         name='mostcommentednewslist'),
    path('client/subcategory/<int:pk>/detail/',
         ClientSubcategoryDetailView.as_view(), name='clientsubcategory'),
    path('editor/<int:pk>/detail/',
         EditorDetailView.as_view(), name='editornewsdetail'),
    path('search/', SearchView.as_view(), name='searched'),
    path('contact/', ClientContactView.as_view(), name='clientcontact'),
    path('about/',ClientAboutView.as_view(),name='clientabout'),
    path('privacy/policy/',OrganizationPrivacyView.as_view(),name='organizationprivacy'),



    path('subscriber/', SubscriberView.as_view(), name='subscriber'),
    path('commentcreate/<int:pk>/',
         CommentCreateView.as_view(), name='commentcreate'),
    # path('news/<int:pk>/detail/',
    #      ClientNewsDetailView.as_view(), name='clientnewsdetail'),
    # editor url
    # editor url
    # editor url
    # editor url


    path('editor/', EditorHomeView.as_view(), name='editorhome'),
    path('editor/newslist/', EditorNewsList.as_view(), name='newslist'),

    # editor news
    # editor news 
    # editor news
    # editor news
    path('editor/<int:pk>/newsdetail',
         EditorNewsDetailView.as_view(), name='newsdetail'),
    path('ajax/load-subcategories/', views.load_subcategories,
         name='load_subcategories'),
    path('editor/newsadd/',
         EditorNewsCreate.as_view(), name='newsadd'),
    path('editor/<int:pk>/newsupdate/',
         EditorNewsUpdate.as_view(), name='newsupdate'),
    path('editor/<int:pk>/newsdelete/',
         EditorNewsDelete.as_view(), name='newsdelete'),
    path('editor-registration/',
         EditorRegistrationView.as_view(), name='editorregistration'),
    path('login/',
         LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('admin/<int:pk>/edit/', EditUserProfileView.as_view(),
         name="edit-user-profile"),
    path('editor/<int:pk>/edit/', EditUsersProfileView.as_view(),
         name="editor-user-profile"),
    path("password/change/",
         PasswordChangeView.as_view(), name="passwordchange"),
    path("editor-password/change/",
         EditorPasswordChangeView.as_view(), name="editorpasswordchange"),


    # admin url
    # admin url
    # admin url
    # admin url

    # admin advertizementposition
    # admin advertizementposition
    # admin advertizementposition
    # admin advertizementposition

    path('adminhome/', AdminView.as_view(), name='adminhome'),
    path('admin/adminadvetizementposition',
         AdminAdvertizementPositionList.as_view(), name='advertizementposition'),
    path('admin/advertizementpositionadd',
         AdminAdvertizementPositionCreate.as_view(), name='advertizementpositionadd'),
    path('admin/<int:pk>/advertizementpositionupdate',
         AdminAdvertizementPositionUpdate.as_view(), name='advertizementpositionupdate'),
    path('admin/<int:pk>/advertizementpositiondelete',
         AdminAdvertizementPositionDelete.as_view(), name='advertizementpositiondelete'),

    # admin advertizement
    # admin advertizement
    # admin advertizement
    # admin advertizement

    path('admin/adminadvettizement',
         AdminAdvertizementList.as_view(), name='advertizement'),
    path('admin/advertizementadd',
         AdminAdvertizementCreate.as_view(), name='advertizementadd'),
    path('admin/<int:pk>/advertizementupdate',
         AdminAdvertizementUpdate.as_view(), name='advertizementupdate'),
    path('admin/<int:pk>/advertizementdelete',
         AdminAdvertizementDelete.as_view(), name='advertizementdelete'),
    path('admin-registration/', AdminRegistrationView.as_view(),
         name='adminregistration'),

    # admin organizationinformation
    # admin organizationinformation
    # admin organizationinformation
    # admin organizationinformation
    path('admin/organizationinformation',
         AdminOrganizationInformationList.as_view(), name='organizationinformationlist'),

    path('admin/<int:pk>/organizationinformationdetail',
         AdminOrganizationInformationDetail.as_view(), name='organizationinformationdetail'),
    path('admin/<int:pk>/organizationinformationupdate',
         AdminOrganizationInformationUpdate.as_view(), name='organizationinformationupdate'),

    # admin newscategory
    # admin newscategory
    # admin newscategory
    # admin newscategory

    path('admin/newscategory/',
         AdminNewsCategoryList.as_view(), name='adminnewscategory'),
    path('admin/newscategoryadd',
         AdminNewsCategoryCreate.as_view(), name='adminnewscategoryadd'),
    path('admin/<int:pk>/newscategoryupdate/',
         AdminNewsCategoryUpdate.as_view(), name='adminnewscategoryupdate'),
    path('admin/<int:pk>/newscategorydelete/',
         AdminNewsCategoryDelete.as_view(), name='adminnewscategorydelete'),

    # admin newssubcategory
    # admin newssubcategory
    # admin newssubcategory
    # admin newssubcategory

    path('admin/newssubcategorylist/',
         AdminNewsSubCategoryList.as_view(), name='adminnewssubcategorylist'),
    path('admin/newssubcategoryadd',
         AdminNewsSubCategoryCreate.as_view(), name='adminnewssubcategoryadd'),
    path('admin/<int:pk>/newssubcategoryupdate/',
         AdminNewsSubCategoryUpdate.as_view(), name='adminnewssubcategoryupdate'),
    path('admin/<int:pk>/newssubcategorydelete/',
         AdminNewsSubCategoryDelete.as_view(), name='adminnewssubcategorydelete'),


    # admin news
    # admin news
    # admin news
    # admin news

    path('admin/newslist',
         AdminNewsList.as_view(), name='adminnewslist'),
    path('admin/newslist/<int:pk>/', AdminDetailView.as_view(), name='newslist'),
    path('admin/<int:pk>/newsdetail',
         AdminNewsDetailView.as_view(), name='adminnewsdetail'),
    path('admin/newsadd/',
         AdminNewsCreate.as_view(), name='adminnewsadd'),
    path('admin/<int:pk>/newsupdate/',
         AdminNewsUpdate.as_view(), name='adminnewsupdate'),
    path('admin/<int:pk>/newsdelete/',
         AdminNewsDelete.as_view(), name='adminnewsdelete'),

    # admin editor
    # admin editor
    # admin editor
    # admin editor
    path('admin/editorlist',
         EditorList.as_view(), name='editorlist'),
    path('admin/editor',
         EditorDashboardList.as_view(), name='editor'),
    path('admin/editorcreate',
         EditorCreate.as_view(), name='editoradd'),
    path('admin/<int:pk>/editorupdate/',
         EditorUpdate.as_view(), name='editorupdate'),
    path('admin/<int:pk>/editordelete/',
         EditorDelete.as_view(), name='editordelete'),
    path('admin/<int:pk>/editordetail/',
         AdminEditorDetailView.as_view(), name='admineditordetail'),
    path('admin/<int:pk>/detail/',
         AdminDetailsView.as_view(), name='admindetails'),

    # admin admin
    # admin admin
    # admin admin
    # admin admin

    path('admin/adminlist',
         AdminList.as_view(), name='adminlist'),


    path('admineditor/<int:pk>/news-list/',
         AdminEditorNewsListView.as_view(), name='admineditornewslist'),
    path('admineditor/<int:pk>/news-list/detail/',
         AdminEditorNewsListDetailView.as_view(), name='admineditornewslistdetail'),
    path('ajaxadminhome/', AjaxAdminHome.as_view(), name='ajaxadminhome'),


]

newsproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls')),
    path('summernote/', include('django_summernote.urls')),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsapp/models.py
from django.contrib.auth.models import User, Group
from django.db import models
# Create your models here.


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class OrgnizationalInformation(TimeStamp):
    name = models.CharField(max_length=500)
    logo = models.ImageField(upload_to="organization")
    address = models.CharField(max_length=500)
    slogan = models.CharField(max_length=500, null=True, blank=True)
    contact_no = models.CharField(max_length=15)
    alt_contact_no = models.CharField(max_length=500, null=True, blank=True)
    map_location = models.CharField(max_length=500)
    email = models.EmailField(null=True, blank=True)
    about_us = models.TextField()
    privacy_policy = models.TextField(null=True, blank=True)
    show_popup = models.BooleanField(default=False)
    popup_image = models.ImageField(
        upload_to="organization", null=True, blank=True)
    facebook = models.CharField(max_length=500)
    instagram = models.CharField(max_length=500, null=True, blank=True)
    twitter = models.CharField(max_length=500, null=True, blank=True)
    youtube = models.CharField(max_length=500, null=True, blank=True)
    linkedin = models.CharField(max_length=500, null=True, blank=True)
    featured_photo = models.ImageField(upload_to="organization")
    featured_video_link = models.CharField(max_length=500)
    messenger_script = models.TextField(null=True, blank=True)
    google_analytics_script = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Admin(TimeStamp):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=500)
    contact_no = models.CharField(max_length=15)
    address = models.CharField(max_length=500)
    email = models.EmailField(null=True, blank=True)
    image = models.ImageField(
        upload_to='team/admin/', blank=True, null=True)
    about = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        group, group_created = Group.objects.get_or_create(name="Admin")
        self.user.groups.add(group)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.full_name


class Editor(TimeStamp):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=500)
    contact_no = models.CharField(max_length=15)
    address = models.CharField(max_length=500)
    email = models.EmailField(null=True, blank=True)
    image = models.ImageField(
        upload_to='team/editor/', blank=True, null=True)
    about = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        group, group_created = Group.objects.get_or_create(name="Editor")
        self.user.groups.add(group)
        super().save(*args, **kwargs)

    def verified_news(self):
        verified_news = self.news_set.filter(is_verified=True)
        print(verified_news.count())
        return verified_news.count()

    def __str__(self):
        return self.full_name


class NewsCategory(TimeStamp):
    title = models.CharField(max_length=500)
    slug = models.SlugField(unique=True, null=True, blank=True)
    image = models.ImageField(
        upload_to="news/main_category", null=True, blank=True)
    icon_character = models.CharField(max_length=500, null=True, blank=True)
    root = models.ForeignKey(
        'self', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title


class NewsSubCategory(TimeStamp):
    title = models.CharField(max_length=500)
    slug = models.SlugField(unique=True, null=True, blank=True)
    main_category = models.ForeignKey(NewsCategory, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="news/sub_category")
    icon_character = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.title


class NewsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class NewsVerified(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_verified=True)


class News(TimeStamp):
    title = models.CharField(max_length=500)
    main_category = models.ForeignKey(
        NewsCategory, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(
        NewsSubCategory, on_delete=models.CASCADE, null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    image = models.ImageField(upload_to="news/news", null=True, blank=True)
    video_link = models.URLField(max_length=500, null=True, blank=True)
    content = models.TextField()
    view_count = models.BigIntegerField(default=0)
    editor = models.ForeignKey(
        Editor, on_delete=models.SET_NULL, null=True, blank=True)
    admin = models.ForeignKey(
        Admin, on_delete=models.SET_NULL, null=True, blank=True)
    active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)
    objects = NewsManager()
    verified = NewsVerified()

    def __str__(self):
        return self.title


class Comment(TimeStamp):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    commenter = models.CharField(max_length=500)
    email = models.EmailField()
    comment = models.TextField()

    def __str__(self):
        return self.commenter


class AdvertizementPosition(TimeStamp):
    position = models.CharField(max_length=500)
    total_number = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.position


class Advertizement(TimeStamp):
    position = models.ForeignKey(
        AdvertizementPosition, on_delete=models.CASCADE)
    organization = models.CharField(max_length=500)
    image = models.ImageField(upload_to="advertizements")
    link = models.URLField(max_length=500)
    expiry_date = models.DateTimeField(null=True, blank=True)
    view_count = models.BigIntegerField(default=1)
    clicks = models.BigIntegerField(default=1)

    def __str__(self):
        return self.organization


class Subscriber(TimeStamp):
    email = models.EmailField()

    def __str__(self):
        return self.email


class Contact(TimeStamp):
    name = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)
    mobile = models.CharField(max_length=50)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name

templates/admintemplates/admineditorlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block editor %}nav-item active
{% endblock %}

{% block content %}
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
       
        <div class="card">
          <div class="card-header card-header-primary card-header-icon">
            <div class="card-icon">
              <i class="material-icons">people</i>
              <!-- <i class="fa fa-user-friends"></i> -->
            </div>
            <h4 class="card-title">Editors List</h4>
          </div>
          <div class="card-body">
            <div class="toolbar">
             <div>

             </div>
           </div>
           <div class="material-datatables">
              <table id="datatables" class="table table-no-bordered table-hover" cellspacing="0"style="width:100%">
              <thead>
                <tr style="text-align: center;background-color: #2F4F4F;color: #ffffff" class="table table-bordered">
                  <th>Sn.</th>
                  <th>User</th>
                  <th>full name</th>
                  <th>contact_no</th>
                  <th>address</th>
                  <th>email</th>                  
                  <th class="disabled-sorting">About</th>                 
                  <th class="disabled-sorting text-right">Actions</th>
                </tr>
              </thead>
              <tfoot>
                <tr style="text-align: center;">
                <th>sn.</th>
                 <th>User</th>
                 <th>full name</th>
                 <th>contact_no</th>
                 <th>address</th>
                 <th>email</th>
                 <th>about</th>                 
                 <th class="text-right">Actions</th>
               </tr>
             </tfoot>
             <tbody>
               {% for editorlist in admineditorlist %}
               <tr style="text-align: center">
                <td>{{forloop.counter}}.</td>
                <td>{{editorlist.user}}</td>
                <td>{{editorlist.full_name}}</td>
                <td>{{editorlist.contact_no}}</td>
                <td>{{editorlist.address}}</td>
                <td>{{editorlist.email}}</td>                
                <td>
                <a data-remote="{% url 'newsapp:admineditordetail' editorlist.pk %}"href="{% url 'newsapp:admineditordetail' editorlist.pk %}" data-toggle="modal" data-target="#myModal">read me</a>
                </td>
                <td class="text-right">
                  <a href="{% url 'newsapp:editorupdate' editorlist.pk %}" class="btn btn-link btn-primary btn-just-icon edit"><i class="material-icons">edit</i></a>
                  <a data-remote="{% url 'newsapp:editordelete' editorlist.pk %}"href="{% url 'newsapp:editordelete' editorlist.pk %}"class="btn btn-link btn-danger btn-just-icon remove" data-toggle="modal" data-target="#myModal">
                    <i class="material-icons">close</i></a>
                  </td>
             </tr>
             {% endfor %}
             
           </tbody>
         </table>
       </div>
     </div>
     <!-- end content-->
   </div>
   <!--  end card  -->
 </div>
 <!-- end col-md-12 -->
</div>
<!-- end row -->
</div>
</div>

{% endblock %}

templates/admintemplates/adminnewsadd.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block new %}nav-item active{% endblock %}
{% block content %}
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-header-primary card-header-icon">
						<div class="card-icon">
							<i class="material-icons">assignment</i>
						</div>
						<div>
							<h4 style="color: #000000">Add NewsSubCategory</h4>
							<br>

							<form method="post" enctype="multipart/form-data" id ="EditorNewsForm" subcategories-url="{% url 'newsapp:load_subcategories' %}" novalidate>
								{% csrf_token %}

								{{form.as_p}}

								
								<!-- <input type="submit" value="Save"> -->
								<span style="padding-left: 35%"><button type="submit" style="width: 150px;height: 35px">save</button></span>

							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<script>
	$(document).ready(function() {
    $('#id_main_category').select2();

    
});
</script>

<script>
	$("#id_main_category").change(function () {
		// alert('1');
      var url = $("#EditorNewsForm").attr("subcategories-url");  
      var maincategory_id = $(this).val()
      // alert(maincategory_id); 
      $.ajax({                      
        url:url,                    
        data: {
          'main_category': maincategory_id       
        },
        
        success: function (data) {
          
          $("#id_sub_category").html(data);  
          
        }
    });

  });
</script>


{% endblock %}

templates/admintemplates/adminnewscategoryupdate.html
{% extends 'admintemplates/adminbase.html' %}
{% block news %}
nav-item active
{% endblock %} 

{% block content %}


<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-header-primary card-header-icon">
						<div class="card-icon">
							<i class="material-icons">assignment</i>
						</div>
						<div>
							<h4 style="color: #000000">update category</h4>
							<br>
							<form method="post" enctype="multipart/form-data">
								{% csrf_token %}

								{{form.as_p}}

								<!-- <input type="submit" value="Update"> -->
								<span style="padding-left: 25%"><button type="submit" style="width: 150px;height: 35px">update</button></span>

							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>




{% endblock %}

templates/admintemplates/adminnewssubcategoryadd.html
{% extends 'admintemplates/adminbase.html' %}
{% block newscat %}nav-item active{% endblock %}

{% block content %}
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-header-primary card-header-icon">
						<div class="card-icon">
							<i class="material-icons">assignment</i>
						</div>
						<div>
						<h3 style="color: #000000">Add NewsSubCategory</h3>
						<br>
						<form method="post" enctype="multipart/form-data">
							{% csrf_token %}

							{{form.as_p}}

							<!-- <input type="submit" value="Save"> -->
						<span style="padding-left: 25%"><button style="width: 150px;height: 35px" type="submit">save</button></span>

						</form>
					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}

templates/admintemplates/adminnewssubcategorydelete.html
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">&times;</button>
	<h4 class="modal-title">Delete newssubcategory</h4>
</div>
<form method="post" action="{% url 'newsapp:adminnewssubcategorydelete' newssubcategory.pk %}" >
	<div class="modal-body">
    {% csrf_token %}

   <p>Are you sure !! You wanna delete <u>{{object.title}}</u> </p>

    </div>
	<div class="modal-footer">
		<button class="btn btn-primary">Delete</button>
		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

	</div>
</form>

templates/admintemplates/adminnewssubcategoryupdate.html
{% extends 'admintemplates/adminbase.html' %}
{% block newscat %}nav-item active{% endblock %}

{% block content %}

<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card" class="form-control">
					<div class="card-header card-header-primary card-header-icon">
						<div class="card-icon">
							<i class="material-icons">assignment</i>
						</div>
						<div>
							<div >
								<h3 style="color: #000000">Add NewsSubCategory</h3>
									<form method="post" action="" >
										{% csrf_token %}

										{{form.as_p}}

										<!-- <input type="submit" value="Update"> -->
										<span style="padding-left: 25%"><button type="submit" style="width: 150px;height: 35px">update</button></span>

									</form>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>





{% endblock %}

templates/admintemplates/adminnewsupdate.html
{% extends 'admintemplates/adminbase.html' %}
 {% load static %}
{% block new %}nav-item active{% endblock %}
{% block content %}

<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-header-primary card-header-icon">
						<div class="card-icon">
							<i class="material-icons">assignment</i>
						</div>
						<h4 style="color: #000000">update news</h4>
						<br>
						<form method="post"  enctype="multipart/form-data">
							{% csrf_token %}

							{{form.as_p}}

							<input type="submit" value="Update">

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>




{% endblock %}

templates/admintemplates/editor_user_profile.html
{% extends 'admintemplates/editorbase.html' %}
{% load static %}



{% block content %}
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header card-header-primary card-header-icon">
						<div class="card-icon">
							<i class="material-icons">perm_identity</i>
						</div>
						<h4 style="color: #000000">edit Profile</h4>
					</div>
					<div class="card card-body">
						<form method="POST" enctype="multipart/form-data">
							{% csrf_token %}
							<!-- {{form.as_p}} -->
							<div class="row">
								<div class="col-md-4">
									username{{form.full_name}}
								</div>
								<div class="col-md-4">
									address{{form.address}}
								</div>
								<div class="col-md-4">
									contact no.{{form.contact_no}}
								</div>
							</div>
							<br>
							<div class="row">
								<div class="col-md-6">
									email{{form.email}}
								</div>
								<div class="col-md-6">
									image {{form.image}}
								</div>
							</div>
							<br>
							<div class="row">
								<div class="col-md-8">
									about{{form.about}}
								</div>
							</div>
						<span style="padding-left: 35%"><button type="submit" class="btn btn-lg">update</button></span>
						</form>
					</div>
				</div>
			</div>
			<div class="col-md-4">
              <div class="card card-profile">
                <div class="card-avatar">
                  <a>
                    <img class="img" src="{{ user.editor.image.url }}" style="height: 150px" />
                  </a>
                </div>
                <div class="card-body">
                  <h6 class="card-category text-gray">Editor</h6>
                  <h4 class="card-title">{{user.editor.full_name}}</h4>
                  <p class="card-description">
                    {{user.editor.about|safe}}
                  </p>
                  <a href="#" class="btn btn-rose btn-round">read me</a>
                </div>
              </div>
            </div>

		</div>
	</div>
</div>

{% endblock %}

templates/admintemplates/editornewsadd.html
{% extends 'admintemplates/editorbase.html' %}
{% load static %}
  {% block newslist %}
  nav-item active
  {% endblock %}
{% block content %}
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-header-primary card-header-icon">
						<div class="card-icon">
							<i class="material-icons">assignment</i>
						</div>
						<div>
							<h3>Add NewsSubCategory</h3>

							<form method="post" enctype="multipart/form-data" id ="EditorNewsForm" subcategories-url="{% url 'newsapp:load_subcategories' %}" novalidate>
								{% csrf_token %}

								{{form.as_p}}

								
								<!-- <input type="submit" value="Save"> -->
								<button type="submit">submit</button>

							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	$("#id_main_category").change(function () {
      var url = $("#EditorNewsForm").attr("subcategories-url");  
      var maincategory_id = $(this).val()
      // alert(maincategory_id); 
      $.ajax({                      
        url:url,                    
        data: {
          'main_category': maincategory_id       
        },
        
        success: function (data) {
          
          $("#id_sub_category").html(data);  
          
        }
    });

  });
</script>


{% endblock %}

templates/admintemplates/editornewsdetail.html
{% extends 'admintemplates/editorbase.html' %}
{% load static %}
{% block newslist %}
nav-item active
{% endblock %}
{% block content %}
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="card card-title">
        <h3 style="text-align: center;">{{newsdetail.title}}</h3>
      </div>
      <div class="card card-body">
        {{newsdetail.content|safe}}
      </div>
      
    </div>
  </div>
</div>
{% endblock %}

templates/admintemplates/passwordchange.html
{% extends "admintemplates/adminbase.html" %}
{% load static %}
{% block content %}
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-header-primary card-header-icon">
						<div class="card-icon">
							<i class="material-icons">assignment</i>
						</div>
						<h4 style="color: black">Change Password</h4>
					</div>
					<div class="card-body">
							{% if error %}
								<li>{{error}}</li>
							{% endif %}	

						<form method="post">
							{% csrf_token %}
							{{form.as_p}}
							<button>Change Password</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}